### ISSUE TITLE
Reduce font size of output panel

### ISSUE THREAD

**Issue by claytonrcarter** [itmecho/atom-phpunit#11]
For me, the 14pt font of the output buffer seems too large. I briefly looked into making the font size of the output panel configurable via settings, but it wasn't immediately clear how to change it since it's in CSS and I'm not very well versed in Atom's API.

Is it possible to manipulate the CSS via the JS API?  Or would it have to be done by defining inline styles when the output panel is created in `AtomPhpunitView`? If I worked on something like this, are you open to a PR?

**Comment by itmecho** [comment]
This is now configurable in v1.3.0
