### ISSUE TITLE
Rerun Last Command

### ISSUE THREAD

**Issue by JeffreyWay** [itmecho/atom-phpunit#13]
Often, I will test a method, and then switch around my app as I try to make it pass. It would be useful if I could, from anywhere, re-trigger my most recent test command. Right now, I'm forced to return to the test class, if I want to re-run the test.

Think this might be easy to add?

**Comment by itmecho** [comment]
Sounds like a good feature! Could store the last command in local storage and then just pull it out again on a new keybinding.

**Comment by itmecho** [comment]
@JeffreyWay This functionality is now in v1.3.0!

**Comment by JeffreyWay** [comment]
Thank you!
