### ISSUE TITLE
"run-test" runs all tests with the same name in the testsuite

### ISSUE THREAD

**Issue by nikazooz** [itmecho/atom-phpunit#3]
Example:
```php

class Example1Test extends \PHPUnit\Framework\TestCase
{
    public function testExample()
    {
        $this->assertTrue(true);
    }
}

class Example2Test extends \PHPUnit\Framework\TestCase
{
    public function testExample()
    {
        $this->assertTrue(true);
    }
}
```

Both "testExample" tests are run.

If you agree that this is not expected behaviour, I'd be happy to make a pull request.

**Comment by itmecho** [comment]
@nikazooz Good spot! Definitely not the expected behaviour :stuck_out_tongue: I pushed a fix for this in v1.2.3, could you confirm it's working for you?

**Comment by nikazooz** [comment]
@Synapse791 It's working great! :) My solution was basically the same.

**Comment by itmecho** [comment]
Excellent! Good to know =] I'm trying to improve my JS and it's nice to know someone else would've done it the same way.
