### ISSUE TITLE
Running a single test does't work when using dataProvider

### ISSUE THREAD

**Issue by claytonrcarter** [itmecho/atom-phpunit#30]
See the `--filter` section of the PHPUnit docs here: https://phpunit.readthedocs.io/en/8.4/textui.html#command-line-options

Basically, PHPUnit uses the output of `__METHOD__` for each test name (eg `TestClass@test_name`) but then adds extra info when running w/ a data provider. (eg `TestClass@test_name with data set #0`). When using this plugin and running a single test, it uses a filter like `test_name$`, which matches `TestClass@test_name` but not `TestClass@test_name with data set #0`. 

I don't have a good solution off the top of my head, but altering the default pattern to be more like `test_name($| with data)` may be a place to start.

**Comment by itmecho** [comment]
Hi @claytonrcarter, this should be covered if we change the filter to `test_name(\swith.+)?$`. 

Would you be interested in becoming a collaborator on this project? I don't have much time to maintain it myself!

**Comment by claytonrcarter** [comment]
I used your suggestion in PR #31. I would be happy to be a collaborator, but I can't promise that I have much time to devote to it either! 😄

**Comment by claytonrcarter** [comment]
BTW thank you!

**Comment by itmecho** [comment]
That's fine, it will be twice as much as if it's just me!
You should have an invite!

You're welcome! Thanks for contributing =]

**Comment by claytonrcarter** [comment]
👋 Hi there again. I'm still open to being a collaborator. I use this package literally everyday, and I've been using a local fork w/ the changes from #28, #29 and #31 w/o issues for a while now.

**Comment by itmecho** [comment]
Hi @claytonrcarter, I invited you as a Collaborator a while ago! Do you want me to resend it?

**Comment by itmecho** [comment]
![image](https://user-images.githubusercontent.com/8384983/135351796-dc569f52-d41a-4a7c-ac36-c2503cc47818.png)

**Comment by claytonrcarter** [comment]
🙄 Sorry. I don't know what I was looking for, but now that I look around, I see that I can indeed merge and close PRs and close issues. I'll get back to this later, but once I have some merges done, I'll probably need you to republish.  Thanks again and sorry for the trouble!

**Comment by itmecho** [comment]
No worries! You'd think they would make it more obvious. Feel free to email me directly and let me know when you're ready for me to publish! I'll have to figure that out again as it was several PCs ago now since I last did it!
